#!/bin/sh
# Start/stop the X13Svc service.
#
### BEGIN INIT INFO
# Provides:          X13Svc
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: X13Home automation system as service
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
#DAEMON=/usr/local/bin/mono-service
DAEMON=/usr/bin/mono-service
NAME=X13Svc
DESC="X13Home automation system as service"

MONOSERVER=$(which mono-service)
X13SVC_FOLDER=/home/mqtt		# <------ CHANGE INSTALL PATH HERE
X13SVC_PID=$(ps auxf | grep X13Svc.exe | grep -v grep | awk '{print $2}')

case "$1" in
 start)
  if [ -z "${X13SVC_PID}" ]; then
   echo  "Starting X13Svc"
   sleep 10
   ${MONOSERVER} -d:${X13SVC_FOLDER}/bin ${X13SVC_FOLDER}/bin/X13Svc.exe
  else
   echo "X13Svc Service is already running!"
  fi
 ;;
 stop)
  if [ -n "${X13SVC_PID}" ]; then
   echo "Stopping X13Svc Service"
   kill ${X13SVC_PID}
  else
   echo "X13Svc Service is not running"
  fi
 ;;
 restart)
  $0 stop
  sleep 1
  $0 start
  stat_done
 ;;
 *)
  echo "usage: $0 {start|stop|restart}"
esac

exit 0
